name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LATEST_OTP_RELEASE: '23.0'

on: [pull_request, push]

jobs:
  linux:
    name: Test with Erlang/OTP ${{ matrix.otp_version }}
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        otp_version: ['19.3', '20.0', '20.3', '21.0', '21.3', '22.0', '22.3', '23.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Erlang
        uses: gleam-lang/setup-erlang@v1.1.0
        with:
          otp-version: ${{ matrix.otp_version }}
      - name: Restore _build and .plt
        uses: actions/cache@v2
        with:
          path: |
            _build
            .plt
          key: ${{ runner.os }}-mix-${{ matrix.otp_version }}-${{ github.sha }}
      - name: Compile
        run: make compile
      - name: Dialyzer
        run: make dialyzer
      - run: make doc
      - name: Test
        run: make test

  latest_otp_release:
    name: Coverage Report and Test Examples
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Erlang
        uses: gleam-lang/setup-erlang@v1.1.0
        with:
          otp-version: ${{ env.LATEST_OTP_RELEASE }}
      - name: Coverage Report
        run: |
          COVER=true make test
          for f in _build/test/covertool/*.xml; do cp "$f" $(basename "${f%.xml}.coverage.xml"); done
          bash <(curl -s https://codecov.io/bash)
      - name: Test Examples
        run: make test-examples